In [1]:
import sys
import pandas as pd
import numpy as np
from Fitter.collinearity import is_pos_def, check_collinearity
from Fitter.fitting import fitting

In [2]:
# calibrate the Hagan SABR model to input data
# The variable results is a dictionary which stores the ivols, ivols_diff(ivols-market ivols) and parameters of SABR 
# for unconstraint calibration and constraint calibration with beta/rho/alpha/vega fixed to specific values
results=fitting('market_data.xlsx')

In [3]:
# read jacobian matrix of calibration from fitting_driver.ipynb
jacmat=results['jacmat']

In [4]:
# check collinearity of the Hagan SABR model by condition no. of Hessian matrix
check_collinearity(jacmat)

The Jacobian matrix is:
[[  5.54644568e-02   1.11242663e-03   5.65540977e-04   0.00000000e+00]
 [  6.29338287e-02  -1.53342262e-05   2.86730938e-05   0.00000000e+00]
 [  4.25465908e-02  -8.70640390e-04  -1.27302483e-04   0.00000000e+00]
 [  3.83935683e-01  -4.12153953e-03  -3.55107819e-02   0.00000000e+00]
 [  6.83718901e-02  -4.96973284e-04  -2.38416065e-03   0.00000000e+00]
 [  1.85497024e-02  -2.40519978e-03  -3.63813090e-03   0.00000000e+00]
 [  1.61461734e-02  -1.66513838e-03  -2.17746641e-03   0.00000000e+00]
 [  1.42026903e-01   1.51897268e-03  -1.37446320e-03   0.00000000e+00]
 [  6.25071056e-02   1.10257219e-03  -3.35237890e-03   0.00000000e+00]
 [  6.85330306e-02   2.49868678e-03  -2.24953034e-03   0.00000000e+00]
 [ -8.15185842e-02  -5.75988827e-03   6.29930091e-03   0.00000000e+00]
 [  2.59842906e-02   4.99724031e-03  -4.44855187e-03   0.00000000e+00]
 [  2.10168259e-02   5.82020293e-05  -3.04183828e-03   0.00000000e+00]
 [ -4.29512157e-03   4.52786146e-04  -9.84569291e-04 