In [1]:
import pandas as pd
import numpy as np
from Fitter.collinearity import is_pos_def, check_collinearity
from Fitter.fitter import Fitter

In [3]:
# calibrate the Hagan SABR model to the input data
# The variable results is a dictionary which stores the ivols and the jacobian matrix calibrated
fitter=Fitter('market_data.xlsx')
fitter.input_read()
results=fitter.calibration()

In [4]:
# read jacobian matrix of calibration from fitting_driver.ipynb
jacmat=results['jacmat']

In [5]:
# check collinearity of the Hagan SABR model by condition no. of Hessian matrix
check_collinearity(jacmat)

The Jacobian matrix is:
[[ -7.20617436e-02   7.62923211e-02   6.53719530e-04  -2.97600403e-04]
 [ -8.45251674e-01   8.50739693e-02  -2.13322928e-03  -2.11850554e-03]
 [ -6.17232288e-01   5.82588781e-02  -2.09504645e-03  -1.45500945e-03]
 [ -1.68891026e+01   5.44467645e-01   5.17974433e-03  -4.54037304e-02]
 [ -5.80003578e-01   6.83718901e-02  -4.96973284e-04  -2.38416065e-03]
 [ -1.94060289e-01   1.85497024e-02  -2.40519978e-03  -3.63813090e-03]
 [ -2.62586834e-01   1.61461734e-02  -1.66513838e-03  -2.17746641e-03]
 [ -1.19564670e+00   1.42026903e-01   1.51897268e-03  -1.37446320e-03]
 [ -1.35594892e+00   6.25071056e-02   1.10257219e-03  -3.35237890e-03]
 [ -1.10862472e+00   6.85330306e-02   2.49868678e-03  -2.24953034e-03]
 [  1.08267474e+00  -8.15185842e-02  -5.75988827e-03   6.29930091e-03]
 [ -9.81256334e-02   2.59842906e-02   4.99724031e-03  -4.44855187e-03]
 [ -2.22021249e-01   2.10168259e-02   5.82020293e-05  -3.04183828e-03]
 [  1.08940024e-02  -4.29512157e-03   4.52786146e-04 